analytics: {}
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.73536
  lightness: 0.938063
  rhythmicContrast: 0.258578
  saturation: 0.097972
cta: {}
layout_spectrum: 0.972119291459647
name: 'theversion '
opengraph: {}
purpose: {}
typography_spectrum: 0.4092438589919575
