name: 'the version '
favicon: null
layout_spectrum: 0.95787
typography_spectrum: 0.614864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#630f4d'
    - '#6f4f92'
    - '#fefefe'
    - '#a4a0d5'
    - '#302b63'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
