name: 'the version '
favicon: null
layout_spectrum: 0.51235
typography_spectrum: 0.86198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#630f4d'
    - '#6f4f92'
    - '#fefefe'
    - '#a4a0d5'
    - '#302b63'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
