analytics: {}
color:
  brandColors:
    - '#C0A8B0'
    - '#603028'
    - '#985850'
    - '#B45A4B'
    - '#000000'
  brandStrength: 0.939189
  lightness: 0.453828
  rhythmicContrast: 0.558558
  saturation: 0.097972
cta: {}
layout_spectrum: 0.975225
name: 'theversion '
opengraph: {}
purpose: {}
typography_spectrum: 0.4092438589919575
