name: 'the version '
favicon: null
layout_spectrum: 0.95787
typography_spectrum: 0.67627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#C09010'
    - '#A08848'
    - '#E8B018'
    - '#F0D830'
  brandStrength: 0.375
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose:
  - name: null
    item: null
    url: null
