analytics: {}
color:
  brandColors:
    - '#C0D0D8'
    - '#63222F'
    - '#808078'
    - '#C04860'
    - '#D06860'
  brandStrength: 0.09572
  lightness: 0.453828
  rhythmicContrast: 0.199324
  saturation: 0.097972
cta: {}
layout_spectrum: 0.975225
name: 'theversion '
opengraph: {}
purpose: {}
typography_spectrum: 0.4092438589919575
