analytics: {}
color:
  brandColors:
    - '#C0D0D8'
    - '#63222F'
    - '#808078'
    - '#C04860'
    - '#D06860'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.975225
name: 'the version '
opengraph: {}
purpose: {}
typography_spectrum: 0.4092438589919575
