name: 'the version '
favicon: null
layout_spectrum: 0.95787
typography_spectrum: 0.67627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0203'
    - '#fefefe'
    - '#674ea2'
    - '#eb0285'
    - '#b1d337'
  brandStrength: 0.375
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose:
  - name: null
    item: null
    url: null
