analytics: {}
color:
  brandColors:
    - '#000000'
    - '#C09010'
    - '#A08848'
    - '#E8B018'
    - '#F0D830'
  brandStrength: 0.375
  lightness: 0.5625
  rhythmicContrast: 0.75
  saturation: 0.125
cta: {}
layout_spectrum: 0.95787
name: 'the version '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.614864
