name: 'the version '
favicon: null
layout_spectrum: 0.69056
typography_spectrum: 0.4092438589919575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0D0D8'
    - '#63222F'
    - '#808078'
    - '#C04860'
    - '#D06860'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
