analytics: {}
color:
  brandColors:
    - '#630f4d'
    - '#6f4f92'
    - '#fefefe'
    - '#a4a0d5'
    - '#302b63'
  brandStrength: 0.375
  lightness: 0.8125
  rhythmicContrast: 0.5
  saturation: 1
cta: {}
layout_spectrum: 0.87719
name: 'the version '
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.614864
